### ISSUE TITLE
Design panel with mousebites away from pins

### ISSUE THREAD

**Issue by mrangen** [mrangen/RP2040-Breadstick#12]
Avoid v-scoring - depanelling will just lead to ripped pads at edge.
![image](https://github.com/mrangen/RP2040-Breadstick/assets/73085145/e00e5406-3172-41d6-8d15-50967c2aa864)

**Comment by codeman256** [comment]
This was my current plan for panelling. 
![image](https://github.com/mrangen/Raspberry-Breadstick/assets/16764732/5c565fe8-33ed-4291-9fe3-3581b6874de2)

**Comment by mrangen** [comment]
That looks pretty good but I think we might need additional mouse-bites. I'd rather err on the side of too many than too few for the first panels.
![image](https://github.com/mrangen/Raspberry-Breadstick/assets/73085145/fd6f25f1-fcee-4400-995a-64796831d3cf)

**Comment by mrangen** [comment]
We should also look into standard panel sizes and make sure that we're not designing a panel that's awkward or wasteful for typical assembly machines. Might be worth asking the manufacturer to give a penalization recommendation.
