### ISSUE TITLE
Add more paste to USB-C Connector

### ISSUE THREAD

**Issue by mrangen** [mrangen/RP2040-Breadstick#13]
![image](https://github.com/mrangen/RP2040-Breadstick/assets/73085145/03e1adde-605d-44ca-a008-e5983a8dba81)

**Comment by codeman256** [comment]
I'm sure I can do this. is there an estimate on how much more paste? 2x or 1.5x?

**Comment by mrangen** [comment]
Based on how the first assembled batch came out, this should be enough: 
![image](https://github.com/mrangen/Raspberry-Breadstick/assets/73085145/3028f894-ff7e-4287-847b-50f79035a3ed)
