### ISSUE TITLE
Show signals between hierarchical sheets 

### ISSUE THREAD

**Issue by mrangen** [mrangen/RP2040-Breadstick#4]

**Comment by mrangen** [comment]
![image](https://github.com/mrangen/RP2040-Breadstick/assets/73085145/2ec4d4c3-ad08-46dc-893d-63bcd97fdf1c)

**Comment by codeman256** [comment]
What do you figure you want to do with this? make the chip the top page then have the sub circuits the sub pages?

**Comment by mrangen** [comment]
Something like that shows important signals and power routing between sheets like this: https://embeddedcomputing.com/technology/analog-and-power/kicad-hierarchical-sheets-for-enhanced-schematics
